require("basic").load_default_options()

require("plugins")

require("keybindings")

require("plugin-config/nvim-tree")
require("plugin-config/buffer_line")
require("plugin-config/spectre")
require("plugin-config/treesitter")
require("plugin-config/telescope")
require("plugin-config/whichkey")
require("plugin-config/comment")
require("plugin-config/mason")
require("plugin-config/lua_line")
require("plugin-config/notify")
require("plugin-config/nvim-autopairs")
require("plugin-config/table-mode")
require("plugin-config/orgmode")
require("plugin-config/project")
require("plugin-config/dashboard")
require("plugin-config/neoscroll")
require("plugin-config/hop")
-- require("plugin-config/JABS")
require("plugin-config/toggleterm")
require("plugin-config/indent-blankline")
require("plugin-config/coderunner")
require("plugin-config/lazygit")
-- require("plugin-config/neogit")

require("lsp")
require("lsp.cmp")
require("lsp.null-ls")

require("nvim-dap")
